name: Nix Setup
description: Install Nix, setup cachix, and install project dependencies

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v9
      continue-on-error: true
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
      continue-on-error: true
    - name: Install deps (nix develop)
      shell: bash
      env:
        NIXPKGS_ALLOW_UNFREE: "1"
      run: nix develop --command pnpm install --frozen-lockfile
