name: Nix Setup
description: Install Nix and install project dependencies

runs:
  using: composite
  steps:
    - name: Install Nix
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux --no-confirm
        echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
    - name: Install deps (nix develop)
      shell: bash
      run: |
        . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        nix develop .#ci --command pnpm install --frozen-lockfile
